### ISSUE TITLE
TypeError when exporting particular user

### ISSUE THREAD

**Issue by zZebrahz** [darthShadow/watched-tools#3]
I am receiving an error when I export a user that causes the entire script to fail.  Since the JSON is written at the end I can not precisely determine which show trips this up but the runtime error is the following:

```
Traceback (most recent call last):
  File "/opt/scripts/plex-watched-tools//plex_export_watched_history.py", line 470, in <module>
    main()
  File "/opt/scripts/plex-watched-tools//plex_export_watched_history.py", line 431, in main
    user_history = _get_user_server_watched_history(plex_server)
  File "/opt/scripts/plex-watched-tools//plex_export_watched_history.py", line 395, in _get_user_server_watched_history
    _get_show_section_watched_history(section, show_history)
  File "/opt/scripts/plex-watched-tools//plex_export_watched_history.py", line 355, in _get_show_section_watched_history
    if not episode.duration > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

The log shows this as the final entry:

`[PlexWatchedHistoryExporter][26510][2021-04-28T19:22:47Z][DEBUG   ][_get_show_section_watched_history] Fully Watched Episode: Special Edition [plex://episode/5d9c1087cb3ffa001f1d24d3]`

Let me know if there is anything else I can do to help debug, thanks!

**Comment by darthShadow** [comment]
I believe this should be fixed now in the develop branch. Please try and let me know.

**Comment by zZebrahz** [comment]
The process ran successfully with the new develop branch commit, thank you!
